name: GitHub Actions for Python (Django) code base
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
  # push:
  #   branches:
  #     - "master"
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: pip install -r requirements.txt
      - run: bash ${{ github.workspace }}/scripts/ci-run-linting.sh
        shell: bash
      - name: echo values
        run: |
          echo ${{github.ref_name}}
          echo ${{github.ref}}
          echo ${{github.repository}}
          echo ${{github.repository_id}}
          # feature/tag-creation
          # refs/heads/feature/tag-creation
          # prabhpreet332/github-ci-cd
          # 593613456
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}


#   unittests:
#     name: Unit Tests
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - name: Install the dependencies
#         run: pip install -r requirements.txt
#       - run: echo "unit tests successful"
#     needs:
#       - linting

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install the dependencies
        run: pip install -r requirements.txt
      - name: Docker Login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker Build and Push 
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: ${{ github.repository }}
          IMAGE_TAG: ${{ github.ref }}
        run: |
          bash ${{ github.workspace }}/scripts/build-image.sh $DOCKER_USERNAME $IMAGE_NAME $IMAGE_TAG

