name: GitHub Actions for Python (Django) code base
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'check-version'

jobs:
  test-job:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - run: >
           git diff --name-only
           if ! git diff --name-only | grep -w "version.txt"; then
              echo "version file not updated" >&2
              exit 1;
           fi 

