name: GitHub Actions for Python (Django) code base
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - 'check-version'

jobs:
  test-job:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls -alth && sh ./check-version-file.sh

