name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  demo-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: python --version
      - run: python3 --version
      - run: pip --version
      - run: pip install -U pip setuptools wheel
      - run: pip list
      - run: ls -alth
      - run: pwd
      - run: echo $PATH
      - run: pip install -r requirements.txt
      - run: pip list
      - run: pip freeze
      - run: echo "🍏 This job's status is ${{ job.status }}."

  main-action:
    runs-on: ubuntu-latest
    steps:
      - run: pip freeze
      - run: ls -alth ${GITHUB_WORKSPACE}/
      - run: bash ${GITHUB_WORKSPACE}/scripts/ci-run.sh
      - run: pip install -r requirements.txt
    needs:
      - demo-action